### PR TITLE
Allows pagination options to be passed to projectList function

### LINKED ISSUE #3: projectList Pagination?
`projectList` returns just the first 100 projects

https://wistia.com/doc/data-api#projects_list
https://wistia.com/doc/data-api#paging_and_sorting_responses

### PR DESCRIPTION
**Pull request by alanshaw**
Optional param so can be released as semver minor

resolves #3

### CODE REVIEW

**Comment by alanshaw** [comment]
Thanks for merging, any chance you can publish?

**Comment by xmaestro** [comment]
Thanks for the PR. I doubt i'll have time to publish though. In any case, i have added you to list of publishers. Let me know if you run into any access issues.

**Comment by alanshaw** [comment]
I need to update the version number - you want me to send a PR or add me as a collaborator?

**Comment by xmaestro** [comment]
Ok. I have added you as a collaborator on GitHub as well. Also you are a collaborator on npmjs now.

**Pull request merged**
